version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend.Dockerfile
    container_name: tala_backend
    ports:
      - "8082:8082"
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_KEY: base64:randomkeyhere=
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/html/database/database.sqlite
    volumes:
      - ./backend:/var/www/html
    command: php -S 0.0.0.0:8082 -t public

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend.Dockerfile
    container_name: tala_frontend
    ports:
      - "8083:8083"
    environment:
      VITE_API_URL: "http://localhost:8082/api"
    volumes:
      - ./frontend:/app:delegated
      - /app/node_modules        # evita el problema!
    command: pnpm run dev --host 0.0.0.0 --port 8083


volumes:
  backend_data: {}
